# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('priority', models.CharField(choices=[('A', 'Critical'), ('B', 'Major'), ('C', 'Minor'), ('O', 'No priority')], max_length=1)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
